qms/Controllers/BreakTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qms.Models;

namespace qms.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BreakTypesController : Controller
    {
        //private qmsEntities db = new qmsEntities();
        private BLL.BLLBreakType dbManager = new BLL.BLLBreakType();
        // GET: BreakTypes
        public ActionResult Index()
        {
            return View(dbManager.GetAll());
        }

        // GET: BreakTypes/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblBreakType tblBreakType = await db.tblBreakTypes.FindAsync(id);
        //    if (tblBreakType == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblBreakType);
        //}

        // GET: BreakTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BreakTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "break_type_id,break_type_short_name,break_type_name,start_time,end_time,duration")] tblBreakType tblBreakType)
        {
            if (ModelState.IsValid)
            {
                dbManager.Create(tblBreakType);
                return RedirectToAction("Index");
            }

            return View(tblBreakType);
        }

        // GET: BreakTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBreakType tblBreakType = dbManager.GetById(id.Value);
            if (tblBreakType == null)
            {
                return HttpNotFound();
            }
            return View(tblBreakType);
        }

        // POST: BreakTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "break_type_id,break_type_short_name,break_type_name,start_time,end_time,duration")] tblBreakType tblBreakType)
        {
            if (ModelState.IsValid)
            {
                dbManager.Edit(tblBreakType);
                return RedirectToAction("Index");
            }
            return View(tblBreakType);
        }

        // GET: BreakTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBreakType tblBreakType = dbManager.GetById(id.Value);
            if (tblBreakType == null)
            {
                return HttpNotFound();
            }
            return View(tblBreakType);
        }

        // POST: BreakTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblBreakType tblBreakType = dbManager.GetById(id);
            dbManager.Remove(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

qms/Views/BreakTypes/Create.cshtml
@model qms.Models.tblBreakType
@{
    ViewBag.Title = "Break Type Create";
}

<div class="container">
    <div class="row">

        <h4 class="page-head-line">Break Type > Create </h4>

        <div class="col-md-5">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.break_type_short_name, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.break_type_short_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Short Name" } })
                            @Html.ValidationMessageFor(model => model.break_type_short_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.break_type_name, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.break_type_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Full Name" } })
                            @Html.ValidationMessageFor(model => model.break_type_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                            @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                            @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control", @placeholder = "Duration (Minuites)" } })
                            @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8">
                            <input type="submit" value="Create" class="btn btn-color" />
                            <button class="btn btn-color">
                                @Html.ActionLink("Back to List", "Index")
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

qms/Views/BreakTypes/Delete.cshtml
@model qms.Models.tblBreakType
@{
    ViewBag.Title = "Break Type Delete";
}


<div class="container">
    <div class="row">
        <h4 class="page-head-line">Break > Delete</h4>
        <hr />
        <div class="col-lg-offset-3 col-md-6">
            <h3>Are you sure you want to delete this?</h3>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.break_type_short_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.break_type_short_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.break_type_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.break_type_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.start_time)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.start_time)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.end_time)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.end_time)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.duration)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.duration)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-offset-1 form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-color" /> 
                    <button class="btn btn-color">
                        @Html.ActionLink("Back to List", "Index")
                    </button>
                </div>
            }
        </div>
</div>
</div>
<br />

qms/Views/BreakTypes/Details.cshtml
@model qms.Models.tblBreakType
@{
    ViewBag.Title = "Break Type Detail";
}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> Break Type Details</title>
</head>
<body>
    <div>
        <h4>tblBreakType</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.break_type_short_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.break_type_short_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.break_type_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.break_type_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.start_time)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.start_time)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.end_time)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.end_time)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.duration)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.duration)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.break_type_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

qms/Views/BreakTypes/Edit.cshtml
@model qms.Models.tblBreakType
@{
    ViewBag.Title = "Break Type Edit";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Break Type > Edit</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.break_type_id)

                <div class="form-group">
                    @Html.LabelFor(model => model.break_type_short_name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.break_type_short_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.break_type_short_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.break_type_name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.break_type_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.break_type_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                        @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                        @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Save" class="btn btn-color" />
                        <button class="btn btn-color">
                            @Html.ActionLink("Back to List", "Index")
                        </button>
                    </div>
                </div>
            </div>
        }


    </div>
</div>

qms/Views/BreakTypes/Index.cshtml
@model IEnumerable<qms.Models.tblBreakType>
@{
    ViewBag.Title = "Break Type List";
}

<br />

<div class="container">
    <div class="row">
        <h4 class="page-head-line">Break > List </h4>

        
        <a href='@Url.Action("Create", "BreakTypes")' style="margin-bottom : 10px;">
            <button class="btn btn-color" style="margin-bottom : 10px;">Create New Break Type</button>
        </a>

        <div class="col-md-12 scrollbar" style="overflow-x: hidden; overflow-y: scroll; max-height: 400px; height: auto">

            <table class="table table-hover table-bordered" id="data">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.break_type_short_name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.break_type_name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.start_time)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.end_time)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.duration)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.break_type_short_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.break_type_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.start_time)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.end_time)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.duration)
                        </td>
                        <td>
                            <button class="btn btn-color">
                                @Html.ActionLink("Edit", "Edit", new { id = item.break_type_id })
                            </button>
                            <button class="btn btn-color">
                                @Html.ActionLink("Delete", "Delete", new { id = item.break_type_id })
                            </button>
                        </td>
                    </tr>
                }

            </table>
        </div>

    </div>
    </div>