qms/Controllers/ServiceSubTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qms.Models;

namespace qms.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ServiceSubTypesController : Controller
    {
       
        private BLL.BLLServiceSubType dbManager = new BLL.BLLServiceSubType();
        private BLL.BLLServiceType dbService = new BLL.BLLServiceType();
        // GET: ServiceSubTypes
        public  ActionResult Index()
        {
            return View(dbManager.GetAll());
            //var tblServiceSubTypes = db.tblServiceSubTypes.Include(t => t.tblServiceType);
            //return View(await tblServiceSubTypes.ToListAsync());
        }

        [AllowAnonymous]
        public JsonResult GetByTypeId(int service_type_id)
        {
            var subTypes = dbManager.GetByTypeId(service_type_id);
            return Json(new { Success = true, serviceSubTypes = subTypes }, JsonRequestBehavior.AllowGet);

        }

        // GET: ServiceSubTypes/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblServiceSubType tblServiceSubType = await db.tblServiceSubTypes.FindAsync(id);
        //    if (tblServiceSubType == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblServiceSubType);
        //}

        // GET: ServiceSubTypes/Create
        public ActionResult Create()
        {
         
        ViewBag.service_type_id = new SelectList(dbService.GetAll(), "service_type_id", "service_type_name");
            return View();
        }

        // POST: ServiceSubTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "service_sub_type_id,service_type_id,service_sub_type_name,max_duration")] tblServiceSubType tblServiceSubType)
        {
            
            if (ModelState.IsValid)
            {
                //db.tblServiceSubTypes.Add(tblServiceSubType);
                //await db.SaveChangesAsync();
                dbManager.Create(tblServiceSubType);
                return RedirectToAction("Index");
            }

            ViewBag.service_type_id = new SelectList(dbService.GetAll(), "service_type_id", "service_type_name", tblServiceSubType.service_type_id);
            return View(tblServiceSubType);
        }

        // GET: ServiceSubTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblServiceSubType tblServiceSubType = dbManager.GetById(id.Value);
            if (tblServiceSubType == null)
            {
                return HttpNotFound();
            }
            ViewBag.service_type_id = new SelectList(dbService.GetAll(), "service_type_id", "service_type_name", tblServiceSubType.service_type_id);
            return View(tblServiceSubType);
        }

        // POST: ServiceSubTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "service_sub_type_id,service_type_id,service_sub_type_name,max_duration")] tblServiceSubType tblServiceSubType)
        {
            if (ModelState.IsValid)
            {
                dbManager.Edit(tblServiceSubType);
                return RedirectToAction("Index");
            }
            ViewBag.service_type_id = new SelectList(dbService.GetAll(), "service_type_id", "service_type_name", tblServiceSubType.service_type_id);
            return View(tblServiceSubType);
        }

        // GET: ServiceSubTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblServiceSubType tblServiceSubType = dbManager.GetById(id.Value);
            if (tblServiceSubType == null)
            {
                return HttpNotFound();
            }
            return View(tblServiceSubType);
        }

        // POST: ServiceSubTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblServiceSubType tblServiceSubType = dbManager.GetById(id);
            dbManager.Remove(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

qms/Views/ServiceSubTypes/Create.cshtml
@model qms.Models.tblServiceSubType
@{
    ViewBag.Title = "Service Create";
}

<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Sub Type > Create </h4>
        <div class="col-md-5">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.service_type_id, null, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.DropDownList("service_type_id", null, "Select One Service Type", htmlAttributes: new { @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.service_type_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.service_sub_type_name, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.service_sub_type_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Service Name" } })
                            @Html.ValidationMessageFor(model => model.service_sub_type_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.max_duration, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.max_duration, new { htmlAttributes = new { @class = "form-control", @placeholder = "Duration (minuites)" } })
                            @Html.ValidationMessageFor(model => model.max_duration, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8">
                            <input type="submit" value="Create" class="btn btn-color" />
                            <button class="btn btn-color">
                                @Html.ActionLink("Back to List", "Index")
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    
</div>

qms/Views/ServiceSubTypes/Delete.cshtml
@model qms.Models.tblServiceSubType

    @{
        ViewBag.Title = "Service Sub Type Delete";
    }
    <div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Sub Type > Delete</h4>
        <hr />
        <div class="col-lg-offset-3 col-md-6">
            <h3>Are you sure you want to delete this?</h3>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.service_sub_type_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.service_sub_type_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.max_duration)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.max_duration)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.tblServiceType.service_type_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tblServiceType.service_type_name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-offset-1 form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-color" />
                    <button class="btn btn-color">
                        @Html.ActionLink("Back to List", "Index")
                    </button>
                </div>
            }
        </div>
    </div>
</div>
<br />
<div></div>

qms/Views/ServiceSubTypes/Details.cshtml
@model qms.Models.tblServiceSubType
@{
    ViewBag.Title = "Service Detail";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>tblServiceSubType</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.service_sub_type_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.service_sub_type_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.max_duration)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.max_duration)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.tblServiceType.service_type_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.tblServiceType.service_type_name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.service_sub_type_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

qms/Views/ServiceSubTypes/Edit.cshtml
@model qms.Models.tblServiceSubType

@{
    ViewBag.Title = "Service Sub Type Edit";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Sub Type > Edit</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.service_sub_type_id)

                <div class="form-group">
                    @Html.LabelFor(model => model.service_type_id, null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.DropDownList("service_type_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.service_type_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.service_sub_type_name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.service_sub_type_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.service_sub_type_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.max_duration, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.max_duration, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.max_duration, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Save" class="btn btn-color" />
                        <button class="btn btn-color">
                            @Html.ActionLink("Back to List", "Index")
                        </button>
                    </div>
                </div>
            </div>
        }


    </div>
</div>

qms/Views/ServiceSubTypes/Index.cshtml
@*@model IEnumerable<qms.Models.tblServiceSubType>*@
@model IEnumerable<qms.ViewModels.VMServiceType>

@{
    ViewBag.Title = "Service List";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Sub Type > List</h4>

        
        <a href='@Url.Action("Create", "ServiceSubTypes")' style="margin-bottom : 10px;">
            <button class="btn btn-color" style="margin-bottom : 10px;">Create New Service</button>
        </a>
        <div class="col-md-12 scrollbar table-scroll">

            <table class="table table-hover table-bordered" id="data">
                <tr>
                    <th>
                        Type Name
                    </th>
                    <th>
                        Service Name
                    </th>
                    <th>
                        Duration(Minutes)
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.service_type_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.service_sub_type_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.max_duration)
                        </td>
                        <td>
                            <button class="btn btn-color">
                                @Html.ActionLink("Edit", "Edit", new { id = item.service_sub_type_id })
                            </button>
                            <button class="btn btn-color">
                                @Html.ActionLink("Delete", "Delete", new { id = item.service_sub_type_id })
                            </button>
                        </td>
                    </tr>
                }

            </table>
        </div>

    </div>
    </div>