qms/Controllers/ServiceDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qms.Models;
using Microsoft.AspNet.Identity;
using qms.ViewModels;
using qms.Utility;
using System.Data.SqlClient;
using qms.SignalRHub;

namespace qms.Controllers
{
    [Authorize(Roles = "Admin, Branch Admin, Service Holder")]
    public class ServiceDetailsController : Controller
    {
        //private qmsEntities db = new qmsEntities();
        private BLL.BLLServiceDetail dbManager = new BLL.BLLServiceDetail();
        private BLL.BLLServiceType dbServiceType = new BLL.BLLServiceType();
        private BLL.BLLBranch dbBranch = new BLL.BLLBranch();
        private BLL.BLLCustomer dbCustomer = new BLL.BLLCustomer();
        private BLL.BLLToken dbtoken = new BLL.BLLToken();
        private BLL.BLLDailyBreak dbBreak = new BLL.BLLDailyBreak();





        private BLL.BLLServiceSubType dbServiceSubType = new BLL.BLLServiceSubType();

        // GET: ServiceDetails
        public ActionResult Index()
        {
            ViewBag.branchList = dbBranch.GetAllBranch();

            SessionManager sm = new SessionManager(Session);
            ViewBag.userBranchId = sm.branch_id;

            int? branch_id;
            string user_id;
            if (User.IsInRole("Admin"))
            {
                branch_id = null;
                user_id = null;
            }
            else if (User.IsInRole("Branch Admin"))
            {
                branch_id = sm.branch_id;
                user_id = null;
            }
            else
            {
                branch_id = null;
                user_id = sm.user_id;
            }

            return View(dbManager.GetAllCurrentDate(branch_id, user_id));

        }

   


        public ActionResult Create()
        {
            var servicetype = dbServiceType.GetAll();
            ViewBag.service_type_id = new SelectList(servicetype, "service_type_id", "service_type_name");
            ViewBag.service_sub_type_id = new SelectList(dbServiceSubType.GetAll(), "service_sub_type_id", "service_sub_type_name");
            //ViewBag.ServiceTypeList = new SelectList(dbServiceSubType.GetAll(), "service_sub_type_id", "service_sub_type_name");

            return View();
        }

        
        [HttpPost]
        [Authorize(Roles = "Branch Admin, Service Holder")]
        public JsonResult Create(VMServiceDetails model)
        {
            try
            {
                SessionManager sm = new SessionManager(Session);
                DisplayManager dm = new DisplayManager();
                model.service_datetime = DateTime.Now;
                model.customer_name = model.contact_no;
                model.end_time = DateTime.Now;
                model.user_id = sm.user_id;
                model.counter_id = sm.counter_id;
                if (ModelState.IsValid)
                {
                    dbManager.Create(model);
                }
                // if (!String.IsNullOrEmpty(sm.branch_static_ip))
                //dm.CreateTextFile(sm.branch_id, sm.branch_static_ip);

                return Json(new { Success = true, Message = "Customer Service Information updated on Server" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = "Problem with Information updated, Please Try Again! Error: " + ex.Message }, JsonRequestBehavior.AllowGet);

            }
        }
        [HttpPost]
        [Authorize(Roles = "Branch Admin, Service Holder")]
        public JsonResult Done(VMServiceDetails model)
        {
            try
            {
                SessionManager sm = new SessionManager(Session);
                DisplayManager dm = new DisplayManager();
                int branchId = sm.branch_id;
                
                string counter_no = sm.counter_no;
                model.service_datetime = DateTime.Now;
                model.end_time = DateTime.Now;
                model.user_id = sm.user_id;
                model.counter_id = sm.counter_id;
                if (ModelState.IsValid)
                {
                    dbManager.Create(model);
                }
                // if (!String.IsNullOrEmpty(sm.branch_static_ip))
                //dm.CreateTextFile(sm.branch_id, sm.branch_static_ip);
                NotifyDisplay.SendMessages(branchId, counter_no, "");
                return Json(new { Success = true, Message = "Customer Service Information updated on Server" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = "Problem with Information updated, Please Try Again! Error: " + ex.Message }, JsonRequestBehavior.AllowGet);

            }
        }
        [HttpPost]
        [Authorize(Roles = "Branch Admin, Service Holder")]
        public JsonResult AddService(VMServiceDetails model)
        {
            try
            {
                SessionManager sm = new SessionManager(Session);
                DisplayManager dm = new DisplayManager();
                model.service_datetime = DateTime.Now;
                model.end_time = DateTime.Now;
                model.user_id = sm.user_id;
                model.counter_id = sm.counter_id;
                if (ModelState.IsValid)
                {
                    dbManager.AddService(model);
                }
                // if (!String.IsNullOrEmpty(sm.branch_static_ip))
                //dm.CreateTextFile(sm.branch_id, sm.branch_static_ip);

                return Json(new { Success = true, Message = "Customer Service Information updated on Server" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = "Problem with Information updated, Please Try Again! Error: " + ex.Message }, JsonRequestBehavior.AllowGet);

            }
        }



        [HttpPost]
        public JsonResult NewTokenNo()
        {
            try
            {
                SessionManager sm = new SessionManager(Session);
                int branchId = sm.branch_id;
                int counterid = sm.counter_id;
                string counter_no = sm.counter_no;
                string user_id = sm.user_id;
                long token_id;
                int token_no, is_break;
                string contact_no, service_type, customer_name, address;
                DateTime start_time, generate_time;

                var serviceList = dbManager.GetNewToken(branchId, counterid, user_id, out token_id, out token_no, out contact_no, out service_type, out start_time, out customer_name, out address,out generate_time,out is_break);

                if (serviceList.Count>0)
                {
                    var services = new SelectList(serviceList, "service_sub_type_id", "service_sub_type_name");


                    var customer = new
                    {
                        token = token_no.ToString().PadLeft(ApplicationSetting.PaddingLeft, '0'),
                        start_time = start_time.ToString("hh:mm:ss tt"),
                        tokenid = token_id,
                        serviceType = service_type,
                        mobile_no = contact_no,
                        user_id=user_id,
                        generate_time = generate_time.ToString("hh:mm:ss tt"),
                        call_time= start_time.ToString("hh:mm:ss tt"),
                        IsBreak= is_break,
                        waitingtime = start_time.Subtract(generate_time).ToString(),
                        service_type_id = (serviceList.Count>0? serviceList.FirstOrDefault().service_type_id : 0),
                    customer_name = customer_name,
                        address = address
                    };
                    NotifyDisplay.SendMessages(branchId, counter_no, token_no.ToString());
                    return Json(new { Success = true, Message = customer, Services = services }, JsonRequestBehavior.AllowGet);



                }
                else
                {
                    NotifyDisplay.SendMessages(branchId, counter_no, "");
                    return Json(new { Success = false, Message = "No token for new service!", IsBreak = is_break }, JsonRequestBehavior.AllowGet);
                }


            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        
        [HttpPost]
        public JsonResult CallManualTokenNo(string token_no_string)
        {
            try
            {
                SessionManager sm = new SessionManager(Session);
                int branchId = sm.branch_id;
                int counterid = sm.counter_id;
                string counter_no = sm.counter_no;
                string user_id = sm.user_id;
                long token_id;
                int token_no=Convert.ToInt32(token_no_string);
                string contact_no, service_type, customer_name, address;
                DateTime start_time;

                var serviceList = dbManager.CallManualToken(branchId, counterid, user_id, token_no, out token_id, out contact_no, out service_type, out start_time, out customer_name, out address);

                if (serviceList.Count > 0)
                {
                    var services = new SelectList(serviceList, "service_sub_type_id", "service_sub_type_name");


                    var customer = new
                    {
                        token = token_no.ToString().PadLeft(ApplicationSetting.PaddingLeft, '0'),
                        start_time = start_time.ToString("dd-MMM-yyyy hh:mm:ss tt"),
                        tokenid = token_id,
                        serviceType = service_type,

qms/Views/ServiceDetails/Create.cshtml
@model qms.ViewModels.VMServiceDetails
@using qms.Utility;
@*@model IEnumerable<qms.Models.tblServiceDetail>*@
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@{
    ViewBag.Title = "Customer Service";
    SessionManager sm = new SessionManager(Session);
}
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <input type="hidden" id="hiduserId" name="hidUser" />
        <input type="hidden" id="is_break" name="is_break" />
        <input type="hidden" id="hid_counter_no" name="hid_counter_no" value="@(sm.counter_no)" />
        <div class="page-head-line" style="position:relative; font-weight:bold; padding-bottom:3px">
            <div style="position:relative; float:left">
                <h4>Customer Service > Create Service </h4>
            </div>
            <div style="position:relative; float:right">
                Counter# @(sm.counter_no), &gt;&gt; Token # <span id="update-message"></span>

            </div>
            <div style="clear:both"></div>
        </div>

        <div class="row">
            <div class="form-group">
                <input type="hidden" id="hidtokenNo" name="hidtokenNo" />
                <div class="col-md-2">
                    @*@Html.ActionLink("Take A Break", "Create", "DailyBreaks", new { area = "" }, new { @class = "btn btn-info" })*@
                </div>
                <div class="col-md-8">

                </div>
            </div>
        </div>


        <div class="row" style="text-align:center">
            <div class="col-md-2" style="text-align:center">
                <button type="submit" onclick="Recall()" class="btn-squere-xl  btn-color marzin-bottom" id="newService_btn">
                    <span><i class="fa fa-bullhorn"></i></span> Recall
                </button>


                <button type="submit" onclick="ManualCall()" class="btn-squere-xl  btn-color marzin-bottom" id="manual_call_btn">
                    <span><i class="fa fa-user-plus"></i></span>Call Token
                </button>
                <button type="submit" onclick="Transfer()" class="btn-squere-xl  btn-color marzin-bottom" id="Transfer_btn">
                    <span><i class="fa fa-cart-arrow-down"></i></span>Counter Transfer
                </button>
                <button type="submit" onclick="loadMissingListDialog()" class="btn-squere-xl  btn-color marzin-bottom" id="missing_btn">
                    <span><i class="fa fa-list"></i></span>Missing List
                </button>

            </div>
            <div class="col-md-7" style="text-align:center">


                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                    Token Information
                                </a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <div style="position:relative">
                                    <div style="position:relative; float:left">
                                        Service Type :
                                    </div>
                                    <div style="position:relative; float:right">
                                        @Html.TextBoxFor(m => m.service_type_name, new { @class = "form-control Next", @id = "txtServiceType", @placeholder = "Service Type" })
                                    </div>
                                    <div style="clear:both"></div>
                                </div>
                                <div style="position:relative">
                                    <div style="position:relative; float:left">
                                        Token Issue Time :
                                    </div>
                                    <div style="position:relative; float:right">
                                        @Html.TextBoxFor(m => m.generate_time, new { @class = "form-control Next", @placeholder = "Generation Time", @id = "txtgnTime" })
                                    </div>
                                    <div style="clear:both"></div>
                                </div>
                                <div style="position:relative">
                                    <div style="position:relative; float:left">
                                        Token Call Time :
                                    </div>
                                    <div style="position:relative; float:right">
                                        @Html.TextBoxFor(m => m.call_time, new { @class = "form-control Next", @id = "txtCallTime", @placeholder = "Call Time" })
                                    </div>
                                    <div style="clear:both"></div>
                                </div>
                                <div style="position:relative">

                                    <div style="position:relative; float:left">
                                        Waiting Time :
                                    </div>


                                    <div style="position:relative; float:right">
                                        @Html.TextBoxFor(m => m.waitingtime, new { @class = "form-control Next", @id = "txtWtTime", @placeholder = "Waiting Time" })
                                    </div>
                                    <div style="clear:both"></div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                    Service Information
                                </a>
                            </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body" style="padding-top:5px">
                                <div class="row" style="position:relative; padding-top:10px;">
                                    <div class="col-lg-3 col-md-3 col-sm-3" style="position:relative; float:left; text-align:left">
                                        Service Start Time:
                                    </div>
                                    <div class="col-lg-9 col-md-9 col-sm-9" style="position:relative; float:right">
                                        @Html.TextBoxFor(m => m.start_time, new { @class = "form-control Next", @placeholder = " Service Start Time" })
                                    </div>

                                </div>
                                <div class="row" style="position:relative; padding-top:10px;">
                                    <div class="col-lg-3 col-md-3 col-sm-3" style="position:relative; float:left; text-align:left">
                                        Service:
                                    </div>
                                    <div class="col-lg-9 col-md-9 col-sm-9" style="position:relative; float:right">
                                        <input type="hidden" id="service_sub_type_id" name="service_sub_type_id" />
                                        @Html.TextBoxFor(m => m.service_sub_type_name, new { @class = "form-control Next", @placeholder = "Add a Service" })
                                    </div>

                                </div>
                                <div class="row" style="position:relative; padding-top:10px;">
                                    <div class="col-lg-3 col-md-3 col-sm-3" style="position:relative; float:left; text-align:left">
                                        Mobile No:
                                    </div>
                                    <div class="col-lg-7  col-md-7 col-sm-7" style="position:relative; float:left">
                                        @Html.TextBoxFor(m => m.contact_no, new { @class = "form-control Next", @id = "txtContact", @placeholder = "Mobile No" }) @Html.ValidationMessageFor(m => m.contact_no)
                                    </div>
                                    <div class="col-lg-2  col-md-2 col-sm-2" style="position:relative; float:right; text-align:left">
                                        <button class="btn btn-color" onclick="GetCustomerInformation()">History</button>
                                    </div>

                                </div>
                                <div class="row" style="position:relative; padding-top:10px;">
                                    <div class="col-lg-3 col-md-3 col-sm-3" style="position:relative; float:left; text-align:left">
                                        Issue:
                                    </div>
                                    <div class="col-lg-9 col-md-9 col-sm-9" style="position:relative; float:right">
                                        @Html.TextAreaFor(m => m.issues, 3, 20, new { @class = "form-control Next", @id = "txtIssues", @row = "3", @placeholder = "Issues" }) @Html.ValidationMessageFor(m => m.issues)
                                    </div>

                                </div>
                                <div class="row" style="position:relative; padding-top:10px;">
                                    <div class="col-lg-3 col-md-3 col-sm-3" style="position:relative; float:left; text-align:left">
                                        Solution:
                                    </div>
                                    <div class="col-lg-9 col-md-9 col-sm-9" style="position:relative; float:right">
                                        @Html.TextAreaFor(m => m.solutions, 3, 20, new { @class = "form-control Next", @id = "txtsolutions", @row = "3", @placeholder = "Solutions" }) @Html.ValidationMessageFor(m => m.solutions)
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>

                </div>


            </div>

            <div class="col-md-2" style="text-align:center">
                <button type="submit" onclick="AddService()" class="btn-squere-xl  btn-color marzin-bottom" id="cancel_btn" data-toggle="modal" data-target="#myModalSave">
                    <span><i class="fa fa-plus-square"></i></span>Add Service
                </button>
                <button type="submit" onclick="SaveNext()" class="btn-squere-xl  btn-color marzin-bottom" id="saveNext_btn">
                    <span><i class="fa fa-chevron-circle-right"></i></span>Next
                </button>

                <button type="submit" onclick="CancelNext()" class="btn-squere-xl  btn-color marzin-bottom" id="cancelNext_btn">
                    <span><i class="fa fa-times-circle"></i></span>Customer Missing
                </button>

                <button type="submit" onclick="loadBreakDialog()" class="btn-squere-xl  btn-color marzin-bottom" id="cancel_btn" data-toggle="modal" data-target="#myModalSave">
                    <span><i class="fa fa-coffee"></i></span>Break
                </button>

            </div>
        </div>



    </div>
</div>

<div id="div-history" title="Previous Service History">
    <div id="historyDiv" class="row">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Issues</th>
                    <th>Solutions</th>

                </tr>
            </thead>
            <tbody id="tablebody"></tbody>
        </table>
    </div>
</div>

<div id="div-services" title="Service List">
    <div id="div-type">
        @Html.DropDownList("service_type_id", null, htmlAttributes: new { @class = "form-control", @placeholder = "Service Types" })
    </div>
    <div id="div-sub-type" class="row" style="border:1px solid #EAEAEA;
            padding-top:5px;
            text-align:left;
            padding-left:5px;
            margin-top:25px;
            margin-right:0px;
            margin-left:0px;">

    </div>

</div>
<div id="dialog-url-break" title="Information">

</div>

<div id="dialog-url-skipped" title="Information">

</div>

<div id="dialog-message" title="Information">
    <div id="body">

    </div>
</div>

@section scripts{

    <script src="~/Scripts/modal/jquery-1.12.4.js"></script>
    <script src="~/Scripts/modal/jquery-ui.js"></script>
    <script src="~/Scripts/modal/modal.js"></script>
    <script src="~/Scripts/modal/tab.js"></script>

    <script src="~/Scripts/modal/bootstrap.min.js"></script>

    <script src="~/Scripts/sqms/date.js"></script>
    <script src="~/Scripts/sqms/service-details.js"></script>

}

qms/Views/ServiceDetails/Details.cshtml
@model qms.Models.tblServiceDetail
@{
    ViewBag.Title = "Service Detail Info";
}
<div>
    <h4>ServiceDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Customer Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCustomer.customer_name)
        </dd>

        <dt>
            @Html.DisplayName("Contact No")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTokenQueue.contact_no)
        </dd>

        <dt>
            @Html.DisplayName("Issues")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.issues)
        </dd>

        <dt>
            @Html.DisplayName("Solution")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.solutions)
        </dd>

        <dt>
            @Html.DisplayName("Service Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_datetime)
        </dd>

        
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.service_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

qms/Views/ServiceDetails/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<qms.ViewModels.VMServiceDetails>
@{
    ViewBag.Title = "Service Detail List";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service > List</h4>
        @if (!(User.IsInRole("Admin") || User.IsInRole("Branch Admin")))
        {
            <a href='@Url.Action("Create", "ServiceDetails")' style="margin-bottom : 10px;">
                <button class="btn btn-color" style="margin-bottom : 10px;">Generate Service</button>
            </a>
        }

        @*<div class="col-md-12">
            <fieldset>

                <table>
                    <tr>
                        <td>As on Date</td>
                        <td>
                            <input type="text" class="dateTimePicker form-control" id="txtAsOnDate" />
                        </td>
                        <td>
                            <input type="button" value="Find" class="btn btn-info" onclick="GetList();" />
                        </td>
                    </tr>
                </table>

            </fieldset>
            <div id="dvList"></div>

        </div>*@

        <div class="form-group">

            <div class="col-md-3" style="margin-bottom : 10px;">
                @*@Html.Label("", new { @class = "col-md-3 control-label" })*@
                <select name="branch_name" class="form-control" id="branch_name">
                    <option value="">All Branch</option>
                    @foreach (var item in ViewBag.branchList)
                    {
                        if (item.branch_id == ViewBag.userBranchId)
                        {
                            <option value="@item.branch_id" selected="selected">@item.branch_name</option>
                        }
                        else
                        {
                            <option value="@item.branch_id">@item.branch_name</option>
                        }

                    }
                </select>

            </div>
            <div class="col-md-6"></div>
            <div class="col-md-3">
                <input type="text" style="font-size: medium;background-color: lightyellow" class="pull-right col-md-3 form-control" placeholder="Search" id="filterBox" onkeyup="FilterTable()" />
            </div>
        </div>

        <div class="col-md-12 scrollbar table-scroll">

            <table class="table table-hover table-bordered" id="data">

                <tr id="Hedding">
                    <th>
                        @Html.DisplayName("Branch")
                    </th>
                    <th>
                        @Html.DisplayName("Counter")
                    </th>
                    <th>
                        @Html.DisplayName("User Name")
                    </th>
                    <th>
                        @Html.DisplayName("Date")
                    </th>
                    <th>
                        @Html.DisplayName("Start Time")
                    </th>
                    <th>
                        @Html.DisplayName("End Time")
                    </th>
                    <th>
                        @Html.DisplayName("Duration")
                    </th>
                    <th>
                        @Html.DisplayName("Customer Name")
                    </th>
                    <th>
                        @Html.DisplayName("Contact No")
                    </th>

                    @*<th></th>*@
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.branch_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.counter_no)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.service_datetime_string)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.start_time_string)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.end_time_string)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.duration)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.customer_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.contact_no)
                        </td>

                        @*<td>
                           @if (User.IsInRole("Admin"))
                           {
                               @Html.ActionLink("Edit", "Edit", new { id = item.service_id })
                           }
                           else
                           {
                               @Html.DisplayName("Edit")
                           }
                        </td>*@
                    </tr>
                }


            </table>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/sqms/service-index.js"></script>


}