qms/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qms.Models;

namespace qms.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ServiceTypesController : Controller
    {
       
        private BLL.BLLServiceType dbManager = new BLL.BLLServiceType();
       


        // GET: ServiceTypes

        public ActionResult Index()
        {
            return View( dbManager.GetAll());
        }

        [Authorize]
        public JsonResult GetAll()
        {

            return Json(new { Success = true, serviceTypes = dbManager.GetAll() }, JsonRequestBehavior.AllowGet);
            
        }

        // GET: ServiceTypes/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblServiceType tblServiceType = await db.tblServiceTypes.FindAsync(id);
        //    if (tblServiceType == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblServiceType);
        //}

        // GET: ServiceTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServiceTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "service_type_id,service_type_name")] tblServiceType tblServiceType)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.tblServiceTypes.Add(tblServiceType);
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }

        //    return View(tblServiceType);
        //}

        public ActionResult Create([Bind(Include = "service_type_id,service_type_name")] tblServiceType tblServiceType) {

            if (ModelState.IsValid)
            {
                //db.tblServiceTypes.Add(tblServiceType);
                dbManager.Create(tblServiceType);
                return RedirectToAction("Index");
            }

            return View(tblServiceType);
        }
        // GET: ServiceTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblServiceType tblServiceType = dbManager.GetById(id.Value);
            if (tblServiceType == null)
            {
                return HttpNotFound();
            }
            return View(tblServiceType);
        }

        // POST: ServiceTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult Edit([Bind(Include = "service_type_id,service_type_name")] tblServiceType tblServiceType)
        {
            if (ModelState.IsValid)
            {
                dbManager.Edit(tblServiceType);
                return RedirectToAction("Index");
            }
            return View(tblServiceType);
        }

        // GET: ServiceTypes/Delete/5
        public  ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblServiceType tblServiceType = dbManager.GetById(id.Value);
            if (tblServiceType == null)
            {
                return HttpNotFound();
            }
            return View(tblServiceType);
        }

        // POST: ServiceTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  ActionResult DeleteConfirmed(int id)
        {
            tblServiceType tblServiceType = dbManager.GetById(id);
            dbManager.Remove(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

qms/Views/ServiceTypes/Create.cshtml
@model qms.Models.tblServiceType

@{
    ViewBag.Title = "Service Type Create";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Type > Create</h4>
        @*<div class="col-md-2"></div>*@
        <div class="col-md-5">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">

                        @*@Html.LabelFor(model => model.service_type_name, htmlAttributes: new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.service_type_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Type Name" } })
                            @Html.ValidationMessageFor(model => model.service_type_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class=" col-md-8">
                            <input type="submit" value="Create" class="btn btn-color" />
                            <button class="btn btn-color">
                                @Html.ActionLink("Back to List", "Index")
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

   

</div>

qms/Views/ServiceTypes/Delete.cshtml
@model qms.Models.tblServiceType

@{
    ViewBag.Title = "Service Type Delete";
}
    
    <div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Type > Delete</h4>
        <hr />
        <div class="col-lg-offset-3 col-md-6">
            <h3>Are you sure you want to delete this?</h3>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.service_type_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.service_type_name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-offset-1 form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-color" />
                    <button class="btn btn-color">
                        @Html.ActionLink("Back to List", "Index")
                    </button>
                </div>
            }
        </div>
    </div>
</div>
<br />

qms/Views/ServiceTypes/Details.cshtml
@model qms.Models.tblServiceType

@{
    ViewBag.Title = "Service Type Delete";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>tblServiceType</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.service_type_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.service_type_name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.service_type_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

qms/Views/ServiceTypes/Edit.cshtml
@model qms.Models.tblServiceType
@{
    ViewBag.Title = "Service Type Edit";
}
<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Type > Edit</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.service_type_id)

                <div class="form-group">
                    @Html.LabelFor(model => model.service_type_name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.service_type_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.service_type_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Save" class="btn btn-color" />
                        <button class="btn btn-color">
                            @Html.ActionLink("Back to List", "Index")
                        </button>
                    </div>
                </div>
            </div>
        }


    </div>
</div>

qms/Views/ServiceTypes/Index.cshtml
@model IEnumerable<qms.Models.tblServiceType>
@{
    ViewBag.Title = "Service Type List";
}

<div class="container">
    <div class="row">
        <h4 class="page-head-line">Service Type > List</h4>

        
        <a href='@Url.Action("Create", "ServiceTypes")' style="margin-bottom : 10px;">
            <button class="btn btn-color" style="margin-bottom : 10px;">Create New Service Type</button>
        </a>
        <div class="col-md-12 scrollbar table-scroll">

            <table class="table table-hover table-bordered" id="data">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.service_type_id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.service_type_name)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.service_type_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.service_type_name)
                        </td>
                        <td>
                            <button class="btn btn-color">
                                @Html.ActionLink("Edit", "Edit", new { id = item.service_type_id })
                            </button>
                            <button class="btn btn-color">
                                @Html.ActionLink("Delete", "Delete", new { id = item.service_type_id })
                            </button>
                        </td>
                    </tr>
                }
            </table>
        </div>

    </div>
    </div>